### PR TITLE
Strip double quotes from server aliases when needed

### PR DESCRIPTION
**Pull request by filippog**
Work around twemproxy json lack of escaping for keys containing double
quotes.

### CODE REVIEW

**Comment by xavierholt** [comment]
Looks good!  I'd like to make sure it doesn't break valid JSON, though.  Do you have a couple examples of server names and what you'd like them stored as?

**Comment by filippog** [comment]
For sure, we're using a config similar to this (cfr twitter/twemproxy#532)

```
servers:
  - 10.64.32.76:6382:1 "cp-1"
  - 10.64.0.201:6382:1 "cp-2"
```

The resulting metrics in json lack escaping though, e.g.

```
""cp-1"": {"server_eof":0, "server_err":0, "server_timedout":1, "server_connections":1, "server_ejected_a
```

Hope that helps!

**Comment by xavierholt** [comment]
Thanks!  I was a little worried about breaking JSON like this:

```js
{"key1": "", "key2": ""}
```

But looking at it again I see you explicitly disallow "internal" quotes, so that's not a problem.  And all the values that Twemproxy gives back are either objects or numbers anyway.  So thinks for the fix - glad you found this useful!

**Comment by filippog** [comment]
@xavierholt no problem and thanks for merging!

**Pull request merged**
